import {useEffect,useRef,useState} from 'react'
import {STORAGE_KEY,criteriaByCategory,categories,reactions,newDecision,validOptions,scoreDecision,explain,randomOption,completeDecision,readDecisions,formatTime} from './decision'
import './App.css'
import './playground.css'
import './garden.css'
import './atlas.css'
import './discovery.css'
import Guide from './Companion'
import Patterns from './Patterns'
import Home from './Home'
import './desktop.css'
import './blue-world.css'
import './scenery.css'
import Coin from './Coin'
import {motion,useReducedMotion} from 'framer-motion'

function Doodle({variant=0}){const art=[
<><path d="M15 25h34l-3 28H18Z" fill="#FBE1D0"/><path d="M24 26v-6a8 8 0 0 1 16 0v6M15 25h34l-3 28H18Z" stroke="#C49379" strokeWidth="2.3" strokeLinejoin="round"/><path d="m27 39 4 4 7-7" stroke="#D49F84" strokeWidth="2.5" strokeLinecap="round"/></>,
<><path d="M10 31h44c-1 16-12 22-22 22S11 47 10 31Z" fill="#F8E9B3" stroke="#C4AD66" strokeWidth="2"/><path d="M21 23c-5-5 5-6 0-12m12 12c-5-5 5-6 0-12m11 12c-5-5 5-6 0-12" stroke="#D5BE7B" strokeWidth="2" strokeLinecap="round"/></>,
<><rect x="12" y="18" width="40" height="35" rx="8" fill="#EEE3FC" stroke="#A894C8" strokeWidth="2"/><path d="M12 29h40M23 12v12m18-12v12" stroke="#A894C8" strokeWidth="2.5" strokeLinecap="round"/><path d="m26 39 5 5 8-9" stroke="#B9A0DA" strokeWidth="3" strokeLinecap="round"/></>,
<><path d="M10 22c0-8 9-11 20-11s20 5 20 15-11 15-24 14l-10 7v-10c-4-3-6-8-6-15Z" fill="#DFF0DB" stroke="#92B891" strokeWidth="2"/><circle cx="23" cy="25" r="2" fill="#8CAD87"/><circle cx="32" cy="25" r="2" fill="#8CAD87"/><circle cx="41" cy="25" r="2" fill="#8CAD87"/></>,
<><path d="M10 17c9-3 17-1 22 4 6-5 15-7 22-4v33c-8-3-15-2-22 2-7-4-14-5-22-2Z" fill="#E2EBF9" stroke="#97ACCA" strokeWidth="2"/><path d="M32 21v31M17 26l8 2m-8 6 8 2m15-8 8-2m-8 10 8-2" stroke="#ACBDD7" strokeWidth="2" strokeLinecap="round"/></>,
<><path d="m32 9 7 16 17 7-17 7-7 17-7-17L9 32l16-7Z" fill="#FBE6D5" stroke="#D1AB89" strokeWidth="2" strokeLinejoin="round"/><path d="m48 8 1 5 5 1-5 2-1 5-2-5-5-2 5-1Z" fill="#E3C8A1"/></>];
return <svg className="doodle" viewBox="0 0 64 64" fill="none" aria-hidden="true">{art[variant%6]}</svg>}
const screenSteps = {category:1,options:2,criteria:3,rank:3,rate:4,result:5,coin:5,final:5}
const nameOf=(d,id)=>d.options.find(o=>o.id===id)?.label||'—'
const dateOf=d=>new Date(d.completed_at).toLocaleDateString('en-US',{month:'short',day:'numeric'})
function Arrow(){return <span aria-hidden="true">↗</span>}
function ScoreBreakdown({decision}){return <div className="breakdown">{decision.selected_criteria.map((c,i)=><div className="criterion-detail" key={c}><h3><span>#{i+1}</span> {c}</h3>{decision.options.map(o=><div className="star-row" key={o.id}><span>{o.label}</span><span className="stars" aria-label={`${decision.scores[c][o.id]} out of 5`}>{decision.scores[c][o.id]} <span>/ 5</span></span></div>)}</div>)}</div>}
function ScoreList({decision}){return <div className="score-list">{scoreDecision(decision).ranked.map((o,i)=><div className="score-row" key={o.id}><span>{o.label}</span><div className="score-track"><span style={{width:`${o.score}%`}}/></div><strong>{o.score}</strong>{i===0&&<span className="sr-only">Highest score</span>}</div>)}</div>}
export default function App(){
 const reduced=useReducedMotion()
 const [loaded]=useState(()=>{try{return {data:readDecisions(localStorage),error:''}}catch{return {data:[],error:'Your saved decisions could not be read. Reload to retry; existing browser data has not been overwritten.'}}})
 const [decisions,setDecisions]=useState(loaded.data)
 const [storageError,setStorageError]=useState(loaded.error)
 const [view,setView]=useState('home')
 const [draft,setDraft]=useState(null)
 const [detailId,setDetailId]=useState(null)
 const [dragRank,setDragRank]=useState(null)
 const [criterionIndex,setCriterionIndex]=useState(0)
 const [custom,setCustom]=useState('')
 const [customOpen,setCustomOpen]=useState(false)
 const [error,setError]=useState('')
 const [flipping,setFlipping]=useState(false)
 const flipTimer=useRef(null), titleRef=useRef(null)
 const detail=decisions.find(d=>d.id===detailId)
 function reorder(from,to){if(from===null||from===to)return;const ordered=[...draft.selected_criteria];const [item]=ordered.splice(from,1);ordered.splice(to,0,item);patch({selected_criteria:ordered,used_coin_flip:false,coin_flip_result:null,coin_flip_reaction:null,final_choice:null});setDragRank(null)}
 useEffect(()=>{titleRef.current?.focus();window.scrollTo(0,0)},[view,criterionIndex])
 useEffect(()=>()=>clearTimeout(flipTimer.current),[])
 function go(next){clearTimeout(flipTimer.current);setFlipping(false);setError('');setView(next)}
 function start(example=false){setDraft(newDecision(example));setCriterionIndex(0);setCustom('');setCustomOpen(false);go(example?'criteria':'category')}
 function patch(values){setDraft(d=>({...d,...values}))}
 function resetComparison(values){patch({...values,scores:{},used_coin_flip:false,coin_flip_result:null,coin_flip_reaction:null,final_choice:null})}
 function selectCriterion(c){if(draft.selected_criteria.includes(c))resetComparison({selected_criteria:draft.selected_criteria.filter(x=>x!==c)});else if(draft.selected_criteria.length<3)resetComparison({selected_criteria:[...draft.selected_criteria,c]})}
 function addCustom(e){e.preventDefault();const c=custom.trim();if(!c)return;if(draft.selected_criteria.length===3){setError('Choose up to 3 priorities. Remove one to add your own.');return}if([...criteriaByCategory[draft.category],...draft.selected_criteria].some(x=>x.toLowerCase()===c.toLowerCase())){setError('That priority is already listed. Select it below.');return}selectCriterion(c);setCustom('');setCustomOpen(false);setError('')}
 function move(index,direction){const ranked=[...draft.selected_criteria];[ranked[index],ranked[index+direction]]=[ranked[index+direction],ranked[index]];patch({selected_criteria:ranked,used_coin_flip:false,coin_flip_result:null,coin_flip_reaction:null,final_choice:null})}
 function flip(){if(flipping||draft.coin_flip_result)return;const picked=randomOption(draft.options);setFlipping(true);flipTimer.current=setTimeout(()=>{patch({used_coin_flip:true,coin_flip_result:picked,coin_flip_reaction:null});setFlipping(false)},1150)}
 function save(){if(loaded.error){setError('Saving is paused because existing history could not be read. Reload to retry without overwriting it.');return}try{const completed=completeDecision(draft);const next=[completed,...decisions.filter(d=>d.id!==completed.id)];localStorage.setItem(STORAGE_KEY,JSON.stringify(next));setDecisions(next);setStorageError('');setDetailId(completed.id);setDraft(null);go('complete')}catch(e){setError(e.message==='Select your final choice.'?e.message:'Could not save this decision. Your choices are still here. Check browser storage and try again.')}}
 function back(){if(view==='rate'&&criterionIndex>0){setCriterionIndex(criterionIndex-1);return}if(view==='result')setCriterionIndex(2);const previous={category:'home',options:'category',criteria:'options',rank:'criteria',rate:'criteria',result:'rate',coin:'result',final:draft?.used_coin_flip?'coin':'result'};go(previous[view]||'home')}
 function openDetail(id){setDetailId(id);go('detail')}
 const step=screenSteps[view]
 const score=draft&&['result','final','coin'].includes(view)?scoreDecision(draft):null
 return <>{!step&&<header className="app-header"><button className="brand" onClick={()=>go('home')}><span className="brand-mark"><Guide/></span>Decision Sprint</button><nav className="desktop-navigation" aria-label="Main navigation">{['home','atlas','patterns'].map(v=><button key={v} aria-current={view===v?'page':undefined} onClick={()=>go(v)}>{v[0].toUpperCase()+v.slice(1)}</button>)}</nav><details className="device-menu"><summary aria-label="Device and storage information"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><circle cx="12" cy="8" r="4"/><path d="M4 22v-3a8 8 0 0 1 16 0v3"/></svg><span>Your space</span></summary><div><strong>Just on this device</strong><p>Your decisions are saved in this browser. No account needed.</p><span>{decisions.length} saved decisions</span></div></details></header>}
 <motion.main initial={reduced?false:{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{type:"spring",stiffness:220,damping:22}} key={view} className={view==='home'?'home-page':`flow-page view-${view}`}>
 {storageError&&<p className="error" role="alert">{storageError}</p>}
 {view==='home'&&<Home decisions={decisions} draft={draft} onStart={start} onOpen={openDetail} onNavigate={go} onResume={()=>go(draft.category?'options':'category')} onCategory={c=>{const d=newDecision();d.category=c;setDraft(d);setCustom('');setCustomOpen(false);go('options')}} onExample={i=>{const d=newDecision(true);if(i){d.category=i===1?'Food':'Shopping';d.options=d.options.map((o,n)=>({...o,label:(i===1?['Cook at home','Eat out']:['Buy it now','Wait a month'])[n]}));d.selected_criteria=criteriaByCategory[d.category].slice(0,3)}setDraft(d);setCriterionIndex(0);setCustom('');setCustomOpen(false);go('criteria')}}/>}
 {step&&<><div className="flow-nav"><button className="text-button" disabled={flipping} onClick={back}>← Back</button><span>{view==='coin'?'A MOMENT OF CHANCE':`STEP ${step} OF 5`}</span><button className="text-button" onClick={()=>go('home')}>Home</button></div><div className="step-track" aria-label={`Step ${step} of 5`}>{[1,2,3,4,5].map(n=><span key={n} className={`${n<=step?'filled':''} ${n===step?'current':''}`}><i>{n===step?<Guide mood={view==="criteria"?"priorities":view==="rate"?"compare":view==="category"?"category":"ready"}/>:n<step?'✓':n}</i></span>)}</div></>}
 {view==='category'&&<><span className="eyebrow">LET’S NARROW IT DOWN</span><h1 ref={titleRef} tabIndex={-1}>What are you<br/>deciding about?</h1><p className="intro">Big plans or small everyday choices. Start here.</p><div className="category-grid">{categories.map((c,i)=><button key={c} aria-pressed={draft.category===c} className={draft.category===c?'category-selected':''} onClick={()=>{if(draft.category!==c)resetComparison({category:c,selected_criteria:[]});go('options')}}><span className="category-symbol"><Doodle variant={i}/></span><strong>{c}</strong><span>↗</span></button>)}</div></>}
 {view==='options'&&<><span className="eyebrow">{draft.category}</span><h1 ref={titleRef} tabIndex={-1}>What are you<br/>choosing between?</h1><p className="intro">Give each option a name. Two to five is plenty.</p><form className="flow-card" onSubmit={e=>{e.preventDefault();if(!validOptions(draft.options)){setError('Add 2–5 different options. Each option needs a name.');return}patch({options:draft.options.map(o=>({...o,label:o.label.trim()}))});go('criteria')}}><div className="option-inputs">{draft.options.map((o,i)=><label key={o.id}><span className="option-caption"><b>{String.fromCharCode(65+i)}</b> Option {String.fromCharCode(65+i)}</span><div><input required maxLength={60} placeholder={i===0?'e.g. Boston':i===1?'e.g. Stay in NYC':'Another possibility'} value={o.label} onChange={e=>resetComparison({options:draft.options.map(x=>x.id===o.id?{...x,label:e.target.value}:x)})}/>{draft.options.length>2&&<button type="button" className="remove-option" aria-label={`Remove option ${String.fromCharCode(65+i)}`} onClick={()=>resetComparison({options:draft.options.filter(x=>x.id!==o.id)})}>×</button>}</div></label>)}</div>{draft.options.length<5&&<button className="text-button add-option" type="button" onClick={()=>resetComparison({options:[...draft.options,{id:crypto.randomUUID(),label:''}]})}>＋ Add another option</button>}{error&&<p className="error" role="alert">{error}</p>}<button className="primary next">Next <Arrow/></button></form></>}
 {view==='criteria'&&<><span className="eyebrow">{draft.category} · YOUR PRIORITIES</span><h1 ref={titleRef} tabIndex={-1}>What matters most?</h1><p className="intro">Choose the 3 things that matter most for this decision.</p><div className={`selection-count ${draft.selected_criteria.length===3?'complete':''}`}><span>Pick your top three</span><strong>{draft.selected_criteria.length} / 3 selected {draft.selected_criteria.length===3?'✓':''}</strong></div><div className="criteria-grid">{[...criteriaByCategory[draft.category],...draft.selected_criteria.filter(c=>!criteriaByCategory[draft.category].includes(c))].map(c=><button key={c} aria-pressed={draft.selected_criteria.includes(c)} disabled={!draft.selected_criteria.includes(c)&&draft.selected_criteria.length===3} className={draft.selected_criteria.includes(c)?'selected':''} onClick={()=>selectCriterion(c)}>{c}<span>{draft.selected_criteria.includes(c)?'✓':'＋'}</span></button>)}</div><button className="text-button add-option" onClick={()=>setCustomOpen(!customOpen)} aria-expanded={customOpen}>＋ Add your own</button>{customOpen&&<form className="custom-form" onSubmit={addCustom}><label className="sr-only" htmlFor="custom-priority">Custom priority</label><input id="custom-priority" maxLength={40} value={custom} placeholder="What matters to you?" onChange={e=>setCustom(e.target.value)}/><button className="secondary" type="submit">Add</button></form>}{error&&<p role="alert" className="error">{error}</p>}{draft.selected_criteria.length===3&&<section className="top-three-board" aria-label="Rank your top 3"><div className="board-title"><h2>Your Top 3</h2><span>Drag or tap arrows</span></div><div className="rank-list">{draft.selected_criteria.map((c,i)=><div data-rank-index={i} className={`rank-row ${dragRank===i?'dragging':''}`} key={c} draggable onDragStart={e=>{e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',String(i));setDragRank(i)}} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();reorder(dragRank,i)}} onDragEnd={()=>setDragRank(null)}><button type="button" className="rank-number rank-drag" aria-label={`Drag priority ${i+1}: ${c}`} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);setDragRank(i)}} onPointerUp={e=>{const row=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-rank-index]');if(row)reorder(i,Number(row.dataset.rankIndex));else setDragRank(null)}} onPointerCancel={()=>setDragRank(null)}>#{i+1}</button><div><strong>{c}</strong><small>{['Matters most','Next most important','Still important'][i]}</small></div><div className="rank-controls"><button aria-label={`Move ${c} up`} disabled={i===0} onClick={()=>move(i,-1)}>↑</button><button aria-label={`Move ${c} down`} disabled={i===2} onClick={()=>move(i,1)}>↓</button></div></div>)}</div></section>}<button className="primary next" disabled={draft.selected_criteria.length!==3} onClick={()=>{setCriterionIndex(0);go('rate')}}>Compare my options <Arrow/></button></>}
 {view==='rate'&&<><div className="criterion-route" aria-label={`Priority ${criterionIndex+1} of 3`}>{draft.selected_criteria.map((c,i)=><span key={c} className={i===criterionIndex?'current':i<criterionIndex?'done':''}><i>{i<criterionIndex?'✓':i+1}</i>{c}</span>)}</div><span className="eyebrow">{criterionIndex+1} OF 3 · YOUR PRIORITIES</span><h1 ref={titleRef} tabIndex={-1}>Which fits <em>{draft.selected_criteria[criterionIndex]}</em> better?</h1><p className="intro">Considering this priority, rate how well each option works for you.</p><div className="rating-progress" role="status">{draft.options.filter(o=>draft.scores[draft.selected_criteria[criterionIndex]]?.[o.id]).length} / {draft.options.length} options rated <span>1 Poor · 5 Great</span></div><div className="rating-list">{draft.options.map((o,index)=><section className="rating-card" key={o.id}><h2><span className="option-letter">{String.fromCharCode(65+index)}</span>{o.label}</h2><div className="rating-buttons" role="group" aria-label={`Rate ${o.label} for ${draft.selected_criteria[criterionIndex]}`}>{[1,2,3,4,5].map(n=><button key={n} aria-pressed={draft.scores[draft.selected_criteria[criterionIndex]]?.[o.id]===n} className={`${n<=(draft.scores[draft.selected_criteria[criterionIndex]]?.[o.id]||0)?'track-filled':''} ${draft.scores[draft.selected_criteria[criterionIndex]]?.[o.id]===n?'selected':''}`} onClick={()=>patch({scores:{...draft.scores,[draft.selected_criteria[criterionIndex]]:{...draft.scores[draft.selected_criteria[criterionIndex]],[o.id]:n}},used_coin_flip:false,coin_flip_result:null,coin_flip_reaction:null,final_choice:null})}>{n}</button>)}</div><div className="rating-labels"><span>Poor fit</span><span>Great fit</span></div></section>)}</div><button className="primary next" disabled={!draft.options.every(o=>draft.scores[draft.selected_criteria[criterionIndex]]?.[o.id])} onClick={()=>criterionIndex<2?setCriterionIndex(criterionIndex+1):go('result')}>{criterionIndex<2?'Next priority':'See my comparison'} <Arrow/></button></>}
 {view==='result'&&<><section className="best-fit"><div className="winner-route" aria-hidden="true"><Guide mood="celebrate"/></div><span className="eyebrow">{score.tied.length>1?'IT’S A TIE':'YOU’VE GOT CLARITY'}</span><h1 ref={titleRef} tabIndex={-1}>{score.tied.length>1?'More than one good fit.':score.ranked[0].label}</h1><div className="big-score">{score.ranked[0].score}<span>/ 100</span></div><span className="fit-note">Here’s what fits best right now.</span></section><ScoreList decision={draft}/><p className="explanation">{explain(draft)}</p><h2 className="subheading">Why it fits</h2><ScoreBreakdown decision={draft}/><details className="calculation"><summary>How the score works</summary><p>Your #1, #2, and #3 priorities receive weights of 3, 2, and 1. We add your weighted ratings, divide by the maximum of 30, and round to a score out of 100. A score is fit to your ratings, not a probability.</p>{score.tied.length>1&&<p>For recordkeeping, the first tied option in your original order is the recommendation. All tied options are equally supported by your scores.</p>}</details><button className="primary next" onClick={()=>{patch({final_choice:null});go('final')}}>{score.tied.length>1?'Choose my final option':`Choose ${score.ranked[0].label}`} <Arrow/></button><button className="secondary wide coin-cta" onClick={()=>go('coin')}>I still can’t decide</button></>}
 {view==='coin'&&<><span className="eyebrow">THE TIE-BREAKER</span><h1 ref={titleRef} tabIndex={-1}>Let chance choose.<br/><em>Then notice how you feel.</em></h1><p className="intro">A little nudge, not the final word.</p><Coin flipping={flipping} result={draft.coin_flip_result} reaction={draft.coin_flip_reaction}/ >{!draft.coin_flip_result?<button className="primary" disabled={flipping} onClick={flip}>{flipping?'Flipping…':'Flip'}</button>:<div className="coin-response" aria-live="polite"><span className="eyebrow">CHANCE PICKED</span><h2>{nameOf(draft,draft.coin_flip_result)}</h2><fieldset><legend>What was your first reaction?</legend><div className="reaction-buttons">{reactions.map((r,i)=><button key={r} aria-pressed={draft.coin_flip_reaction===r} className={draft.coin_flip_reaction===r?'selected':''} onClick={()=>patch({coin_flip_reaction:r})}><span>{['☺','↘','—'][i]}</span>{r}</button>)}</div></fieldset>{draft.coin_flip_reaction&&<p className="reaction-note" role="status">{draft.coin_flip_reaction==='Relieved'?`That reaction may be telling you something. ${nameOf(draft,draft.coin_flip_result)} may already be the option you were hoping for.`:draft.coin_flip_reaction==='Disappointed'?'Interesting. Feeling disappointed may mean you were hoping for another option.':'The options may genuinely feel close. Either choice may be good enough.'}</p>}<button className="primary next" disabled={!draft.coin_flip_reaction} onClick={()=>{patch({final_choice:null});go('final')}}>Make my final choice <Arrow/></button></div>}</>}
 {view==='final'&&<><span className="eyebrow">THE CALL IS YOURS</span><h1 ref={titleRef} tabIndex={-1}>What’s your<br/>final choice?</h1><p className="intro">The comparison is a guide. You get the last word.</p><div className="final-options" role="group" aria-label="Final choice">{draft.options.map(o=><button key={o.id} aria-pressed={draft.final_choice===o.id} className={draft.final_choice===o.id?'selected':''} onClick={()=>patch({final_choice:o.id})}><span><strong>{o.label}</strong><small>{score.tied.some(t=>t.id===o.id)?score.tied.length>1?'Tied best fit':'Best fit from your ratings':'Your choice is always open'}</small></span><span className="radio-dot">{draft.final_choice===o.id?'✓':''}</span></button>)}</div>{error&&<p className="error" role="alert">{error}</p>}<button className="primary next" disabled={!draft.final_choice} onClick={save}>Lock my decision <span>✓</span></button><p className="local-note">Saved on this device. Just for you.</p></>}
 {view==='complete'&&detail&&<section className="completion"><div className="done-mark"><Guide mood="celebrate"/><span>✧</span><span>✦</span></div><span className="eyebrow">A LITTLE MOMENT TO CELEBRATE</span><h1 ref={titleRef} tabIndex={-1}>Decision made.</h1><p className="completed-choice">{nameOf(detail,detail.final_choice)}</p><p className="intro">You gave it some thought. Now you can let it go.</p>{decisions.length===5&&<div className="milestone">✳ Your decision atlas is ready to explore.</div>}<button className="primary" onClick={()=>go('home')}>Back Home <Arrow/></button><button className="secondary wide" onClick={()=>go('detail')}>View Decision</button></section>}
 {view==='detail'&&detail&&<><button className="text-button back-alone" onClick={()=>go('home')}>← Back Home</button><span className="eyebrow">{detail.category} · {dateOf(detail)}</span><h1 ref={titleRef} tabIndex={-1}>{detail.options.map(o=>o.label).join(' or ')}</h1><div className="detail-choice"><span className="eyebrow">YOUR FINAL CHOICE</span><h2>{nameOf(detail,detail.final_choice)} <span>✓</span></h2></div><h2 className="subheading">Your comparison</h2><ScoreList decision={detail}/><h2 className="subheading">Top 3 priorities</h2><ScoreBreakdown decision={detail}/><div className="detail-facts"><div><span>Recommendation</span><strong>{nameOf(detail,detail.recommended_option)}{scoreDecision(detail).tied.length>1?' (tied best fit)':''}</strong></div><div><span>Coin flip used</span><strong>{detail.used_coin_flip?'Yes':'No'}</strong></div>{detail.used_coin_flip&&<><div><span>Chance picked</span><strong>{nameOf(detail,detail.coin_flip_result)}</strong></div><div><span>First reaction</span><strong>{detail.coin_flip_reaction}</strong></div></>}<div><span>Decision time</span><strong>{formatTime(detail.decision_duration_seconds)}</strong></div></div></>}
 {['atlas','patterns'].includes(view)&&<Patterns key={view} mode={view} decisions={decisions} onOpen={openDetail} onStart={()=>start()}/>}
 <footer><span>Decision Sprint</span><span>Saved on this device</span></footer>
 </motion.main>{['home','atlas','patterns','detail'].includes(view)&&<nav className="bottom-nav" aria-label="Main navigation"><button aria-current={view==='home'?'page':undefined} onClick={()=>go('home')}><span>⌂</span>Home</button><button aria-current={view==='atlas'?'page':undefined} onClick={()=>go('atlas')}><span>⌁</span>Atlas</button><button className="nav-decide" onClick={()=>start()}><span>＋</span>Decide</button><button aria-current={view==='patterns'?'page':undefined} onClick={()=>go('patterns')}><span>⌘</span>Patterns</button></nav>}</>
}
