import {useEffect,useRef,useState} from 'react'
import {motion,useReducedMotion} from 'framer-motion'
export default function DecisionPin({decision,color,muted,onOpen}){
 const [open,setOpen]=useState(false),root=useRef(null),trigger=useRef(null),reduced=useReducedMotion()
 const choice=decision.options.find(o=>o.id===decision.final_choice)?.label||'—'
 const date=new Date(decision.completed_at).toLocaleDateString('en-US',{month:'short',day:'numeric'})
 useEffect(()=>{if(!open)return;const outside=e=>{if(!root.current?.contains(e.target))setOpen(false)};document.addEventListener('pointerdown',outside);return()=>document.removeEventListener('pointerdown',outside)},[open])
 return <div ref={root} className={`pin-wrap ${open?'pin-open':''}`} onKeyDown={e=>{if(e.key==='Escape'){setOpen(false);trigger.current?.focus()}}}><motion.button ref={trigger} whileHover={reduced?{}:{y:-5}} transition={{type:'spring',stiffness:220,damping:18}} className={`world-marker ${muted?'marker-muted':''}`} aria-label={`${choice}, ${decision.category}, ${date}`} aria-expanded={open} onClick={()=>setOpen(!open)}><svg className="illustrated-pin" viewBox="0 0 42 52" fill="none" aria-hidden="true"><ellipse cx="21" cy="47" rx="12" ry="4" fill="#7DABC6" opacity=".2"/><path d="M21 45C15 36 4 27 4 18a17 17 0 0 1 34 0c0 9-11 18-17 27Z" fill={color}/><circle cx="21" cy="18" r="9" fill="#FFFDF8"/><path d="m16 23 10-10m-9 0h9v9" stroke="#6E8DA8" strokeWidth="2" strokeLinecap="round"/></svg><span className="marker-tooltip"><b>{choice}</b>{date} · {decision.coin_flip_reaction||'Comparison'}</span></motion.button>{open&&<div className="pin-popover" role="dialog" aria-label={`Preview ${choice}`}><button className="pin-close" aria-label="Close preview" onClick={()=>{setOpen(false);trigger.current?.focus()}}>×</button><span className="eyebrow">{decision.category}</span><h3>{choice}</h3><p>{decision.options.map(o=>o.label).join(' / ')}</p><small>{date} · {decision.coin_flip_reaction||'Comparison'}</small><button className="text-button" onClick={()=>{setOpen(false);onOpen()}}>View decision →</button></div>}</div>
}
