import {useEffect,useRef,useState} from 'react'
import {categories,getPatterns} from './decision'
import {weeklyCount,shortCategory} from './patternView'
import Companion from './Companion'
import {CategoryObject,CloudCluster} from './Scenes'
import {AnimatePresence,motion,useReducedMotion} from 'framer-motion'
const label=d=>d.options.find(o=>o.id===d.final_choice)?.label
const examples=[['A weekend away','Boston','Stay in NYC'],['What’s for dinner?','Cook at home','Eat out'],['A little upgrade','Buy it now','Wait a month']]
export default function Home({decisions,onStart,onCategory,onOpen,onNavigate,onExample,draft,onResume}){
 const [mood,setMood]=useState('curious'),[thought,setThought]=useState(0)
 const reduced=useReducedMotion()
 useEffect(()=>{if(reduced)return;const timer=setInterval(()=>setThought(n=>(n+1)%2),7000);return()=>clearInterval(timer)},[reduced])
 const [example,setExample]=useState(0),heading=useRef(null)
 useEffect(()=>{heading.current?.focus();if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const nodes=document.querySelectorAll('.play-home-columns>*,.home-footpaths');const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}})},{threshold:.08});nodes.forEach(node=>{node.classList.add('scroll-reveal');observer.observe(node)});return()=>observer.disconnect()},[])
 const now=new Date(),week=decisions.filter(d=>weeklyCount([d],now)>0),p=getPatterns(week),last=decisions[0]
 return <><section className="play-hero"><div className="play-hero-copy"><span className="eyebrow">A CALM PLACE FOR YOUR NEXT CHOICE</span><h1 ref={heading} tabIndex={-1}>What are you<br/>stuck on today<span>?</span></h1><p>Give your options a little room. Find what matters.<br className="desktop-only"/> Take your next step with a clearer head.</p><button className="primary" onPointerEnter={()=>setMood("excited")} onPointerLeave={()=>setMood("curious")} onClick={()=>onStart()}>Start a decision <span>↗</span></button><div className="play-categories">{categories.map((c,i)=><button key={c} onPointerEnter={()=>setMood("thinking")} onPointerLeave={()=>setMood("curious")} onClick={()=>onCategory(c)}><CategoryObject variant={i}/>{shortCategory(c)}</button>)}</div>{draft&&<button className="text-button" onClick={onResume}>Continue your unsaved decision →</button>}</div><div className="dial-scene"><CloudCluster/><span className="hero-hill hill-back"/><span className="hero-hill hill-front"/><svg className="scene-route" viewBox="0 0 450 340" fill="none" aria-hidden="true"><path d="M38 285q100 20 126-65t94-12 146-116" stroke="#B9D1B8" strokeWidth="2" strokeDasharray="3 9"/><circle cx="39" cy="285" r="7" fill="#F3D98B"/><path d="m396 91 14-7-2 15" stroke="#315B45" strokeWidth="2" strokeLinecap="round"/></svg><AnimatePresence mode="wait"><motion.span key={thought} initial={reduced?false:{opacity:0,y:6}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-6}} className="scene-label scene-a">{thought?'Try somewhere new?':'A weekend away?'}</motion.span></AnimatePresence><span className="scene-label scene-b">{thought?'What matters most?':'Keep it simple?'}</span><Companion interactive mood={mood}/><span className="scene-star">✧</span><span className="dial-caption">Meet Decision Dial · give it a spin</span></div></section>
 <section className="example-ribbon"><svg className="ribbon-river" viewBox="0 0 1000 110" preserveAspectRatio="none" aria-hidden="true"><path d="M0 45C80-20 220 50 360 22S660 0 790 26 940 0 1000 33V88C800 130 750 73 540 98S180 73 0 105Z" fill="#E1F2FF"/><path d="M30 81Q170 44 290 70T560 68 820 70 970 47" fill="none" stroke="#A8D2F4" strokeWidth="2" strokeDasharray="2 8"/></svg><CategoryObject variant={[2,1,0][example]}/><span>A small choice to try</span><motion.button initial={reduced?false:{opacity:0,x:12}} animate={{opacity:1,x:0}} transition={{type:"spring",stiffness:220,damping:20}} className="example-bubble" key={example} onClick={()=>onExample(example)}>{examples[example][0]} <span>{examples[example][1]} / {examples[example][2]} ↗</span></motion.button><button className="shuffle-example" aria-label="Show another example" onClick={()=>{setExample((example+1)%examples.length);setMood('happy')}}>↻</button></section>
 <div className="play-home-columns"><section className="play-recents"><div className="section-heading"><h2>Recent decisions</h2><span>{decisions.length} little {decisions.length===1?'step':'steps'} forward</span></div>{last?<><button className="last-receipt" onClick={()=>onOpen(last.id)}><span className="receipt-kicker">YOUR LAST DECISION <time>{new Date(last.completed_at).toLocaleDateString('en-US',{month:'short',day:'numeric'})}</time></span><h3>{label(last)} <span>↗</span></h3><p>{last.options.map(o=>o.label).join(' or ')}</p><div><span>{shortCategory(last.category)}</span><span>Led by {last.selected_criteria[0]}</span><span>{last.used_coin_flip?'A little chance':'Weighted comparison'}</span></div></button><div className="recent-timeline">{decisions.slice(1,5).map(d=><button key={d.id} onClick={()=>onOpen(d.id)}><i/><div><strong>{label(d)}</strong><span>{shortCategory(d.category)} · {new Date(d.completed_at).toLocaleDateString('en-US',{month:'short',day:'numeric'})}</span></div><span>↗</span></button>)}</div></>:<div className="home-empty"><Companion mood="map"/><h3>Your first choice starts the story.</h3><p>Make a decision and find it here whenever you need it.</p></div>}</section>
 <aside className="week-summary"><span className="eyebrow">A MOMENT TO LOOK BACK</span><h2>Your week<span>↗</span></h2><dl><div><dt>Decisions made</dt><dd>{week.length}</dd></div><div><dt>Most common category</dt><dd>{p.categoryCounts.length?p.categoryCounts.filter(([,n])=>n===p.categoryCounts[0][1]).map(([c])=>shortCategory(c)).join(' / '):'Not yet'}</dd></div><div><dt>Decision method</dt><dd>{p.total?`${p.flipped} with a coin flip · ${p.total-p.flipped} comparison only`:'Your next choice starts here'}</dd></div></dl><p className="week-reflection">{p.total?`You kept ${p.priorityCounts[0][0].toLowerCase()} in mind in ${p.priorityCounts[0][1]} of ${p.total} ${p.total===1?'decision':'decisions'} this week.`:'A few decisions will reveal the priorities you return to.'}</p><button className="text-button" onClick={()=>onNavigate('patterns')}>Explore your patterns ↗</button></aside></div>
 <div className="home-footpaths"><button onClick={()=>onNavigate('atlas')}><span>⌁</span><div><h3>A world of your choices</h3><p>Visit your Decision Atlas</p></div>↗</button><button onClick={()=>onStart()}><span>↻</span><div><h3>Still between two good options?</h3><p>Compare first. Let a coin give you a nudge.</p></div>↗</button></div></>
}
